services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    enviroment:
      - REDIS_ARGS=--requirepass dummy123lol --appendonly yes
    ## TODO: remove
    restart: unless-stopped
  aauth:
    build: 
      - ./
    container_name: 
      - aauth
    ports: 
      -'8080:80'
    
  