// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const checkUserExists = `-- name: CheckUserExists :one
SELECT EXISTS(SELECT 1 FROM creds WHERE username = $1)
`

func (q *Queries) CheckUserExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT username, password FROM creds WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (Cred, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i Cred
	err := row.Scan(&i.Username, &i.Password)
	return i, err
}

const register = `-- name: Register :exec
INSERT INTO creds (username, password) VALUES ($1, $2)
`

type RegisterParams struct {
	Username string
	Password string
}

func (q *Queries) Register(ctx context.Context, arg RegisterParams) error {
	_, err := q.db.Exec(ctx, register, arg.Username, arg.Password)
	return err
}
